import Head from 'next/head'
import { getFeaturedEvents } from '@/data/dummyData'
import EventList from '../components/events/EventsList'

export default function Home() {
    const featuredEvents = getFeaturedEvents()

    console.log(featuredEvents)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <EventList items={featuredEvents} />
            </main>
        </>
    )
}
